# Generated by Django 4.0.4 on 2022-05-31 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='gui',
            new_name='guid',
        ),
    ]
